### ISSUE TITLE
MSSQL TestInvalidConnectionDetails is implemented

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1072]
- Test cases
    - expected error propogates when all other deps succeed and this one errors
  - Notes
    - The details of NewConnectionDetails should not be tested here.  We can
      write a separate UT for that func if desired (see mysql connector for an
      example of that)
    - Just create a double for newConnectionDetails which is an error returning
      func.

**Comment by BradleyBoutcher** [comment]
We do not currently have an error path for ConnectionDetails - we ignore any errors.

Our thought so far is that we don't have a way to catch and return an error here without being untruthful to the user. For example, if the user passes in a string for the port in their secretless config, MsSQL returns a specific error. If we catch that prematurely and throw and error from secretless, the user would get an "Unable to connect" error from MsSQL, rather than a malformed parameter error.

For now - we don't have a solution for catching malformed parameters when forming ConnectionDetails without interrupting the expected errors a user might receive.

**Comment by izgeri** [comment]
At current, the client hangs when the Secretless configuration for connection info is invalid.

This is consistent with the other connectors, even if it's not ideal.

We can consider interjecting to return a packet to the client with an error, if we're able to write a meaningful error as if it's from the server (this is true for all existing DB connectors).

For now we won't write these tests (and thus I'm closing the issue), but there is a follow-up issue to meaningfully improve the broker's behavior in this situation in #1097.
