### ISSUE TITLE
There is a plan for adding TLS support for the MSSQL connector

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1153]
# Overview
We know that the client-to-DB connection is more secure when using TLS, but right now Secretless does not support TLS in the secretless-to-MSSQL connection.

We would like to implement support for TLS, but before we do, we need to understand what will be required. In this spike we will:
- Review the pg/mysql connectors to see which parameters are supported
- Map the supported Secretless TLS modes to MSSQL TLS modes / configuration parameters
- Determine what technical work must be completed in order to add support for the TLS modes (leveraging the existing Secretless SSL library, and the go-mssqldb library

Assumptions:
- the MSSQL connector should support TLS as much as the MySQL and PG connectors currently do, but don't need to go beyond that (eg MSSQL doesn't need to support the equivalent modes that MySQL and pg don't currently support - see the [MySQL](https://docs.secretless.io/Latest/en/Content/References/connectors/scl_mysql.htm#Configuretheserviceconnector) and [postgres](https://docs.secretless.io/Latest/en/Content/References/connectors/scl_postgres.htm#Configuretheserviceconnector) documentation, where there is a `Note` listing the modes that are *not* supported)
- the MSSQL connector's TLS should be configurable using the same configuration parameters that pg / mysql use - these configuration parameters are not necessarily the same that the individual DB uses, but using the same parameters (sslmode, sslkey, sslrootcert, sslcert) enables consistent configuration of Secretless across all DB connectors. the docs should clearly map the SSL config to known parameters for configuring the MSSQL client connection in practice, so that it's easy for end users to figure out how to configure secretless.
- the task outline MUST include tasks for documentation, test coverage, and troubleshooting updates

# Definition of done
- [x] This issue has an outline of the tasks required to implement TLS support at the level of the current PG/MySQL connectors in the MSSQL connector
- [ ] The project brief for "MSSQL supports TLS" is updated (eg a table - talk to @alexkalish for format)

**Comment by doodlesbykumbi** [comment]
At present the driver will use encryption if it is available on the server-side. The plan here is to provide more explicit control of encryption.

## TLS Support interface in Secretless

+ sslmode
  This option determines if the connection between Secretless Broker and your database is protected by SSL.

  Supported values are:
  + disable: Only try a non-SSL connection.
  + require: Only try an SSL connection.
  + verify-ca: Only try an SSL connection, and verify that the server certificate is issued by a trusted certificate authority (CA)
+ sslrootcert
  The content of this parameter specifies the SSL certificate authority (CA) certificate(s) in PEM format. If present, the server’s certificate will be verified to be signed by one of these authorities.
+ sslcert
  The content of this parameter specifies the client SSL certificate in PEM format. This parameter is ignored if an SSL connection is not made. Corresponds to ssl-cert.
+ sslkey
  The content of this parameter specifies the secret key used for the client certificate. This parameter is ignored if an SSL connection is not made. Corresponds to ssl-key.

## MSSQL Considerations

The MSSQL driver supports the following options for TLS:
1. Encryption is available but off. This tells the server that if it has TLS then the client is happy to use it, otherwise it's fine.
2. Encryption is available and on. This tells the server that if it has TLS then the client is happy to use it.
3. Encryption is not available. This tells the server to not use TLS.

The driver does not seem to support specifying a client certificate out of the box, but we could certainly add it in. Though it does not seem idiomatic for MSSQL, as far as I can tell.

## Core implementation tasks

Ideally each story  would come with its own set of test cases so that the testing story concludes as the other stories are finished.

- [ ] Initial support for sslmode. For this issue the only value can be `disable`, which means no TLS.
- [ ] Support for sslmode `require` so that TLS must be used.
- [ ] Support for sslmode `verify-ca`, + sslrootcert, so that TLS must be used and the server certificate must be verified.
- [ ] Support for specifying client certificate ?
- [ ] Unit/Integration tests for each sslmode and specifying client certificate 

## Beyond implementation tasks

1. Update connector documentation to reflect TLS support
2. Update troubleshooting to reflect issues surrounding use of TLS support

**Comment by izgeri** [comment]
@doodlesbykumbi this looks great - I'm going to add the implementation tasks / summary you shared above to the epic #1032 - can you please log all the issues and make sure they're linked to that epic? thank you!!

**Comment by BradleyBoutcher** [comment]
@doodlesbykumbi This seems to make sense based on what I know of the MsSQL adapter, and you explained everything well. I think this proposal sounds great.
