### ISSUE TITLE
There is an example generic HTTP connector config for the Google Maps API

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#1259]
## Use case
I am building an app that needs to query the Google Maps API

## Additional details
- [x] There needs to be some way for Secretless to authenticate using HTTP query parameters rather than through Authorization headers

The Google Maps APIs accept an API key through its query params. 

These are the potential APIs that can be supported by a connector that uses our new `queryParams` key/value pair to accept a Google API Key: 

**Routes:**
- [x] Directions API
- [x] Distance Matrix API
- [x] Roads API

**Places:**
- [x] Places API
- [x] Time Zone API
- [x] Geocoding API
- [x] Geolocation API

## Acceptance criteria
- [x] There is a generic HTTP connector config available in the [example generic HTTP connector configs](https://github.com/cyberark/secretless-broker/tree/master/examples/generic_connector_configs) for connecting to Google Maps via Secretless

**Comment by mdodell** [comment]
Many of the Google Maps APIs use an API key that is [passed in via a parameter, i.e. the Directions API](https://developers.google.com/maps/documentation/directions/start), rather than through Authorization headers. 

Based off of discussion, it looks like the generic HTTP connector would require support for query parameters.
