### ISSUE TITLE
MacOS CI keychain error has been resolved

### ISSUE THREAD

**Issue by jtuttle** [cyberark/secretless-broker#1422]
While attempting to release v1.7.5 I had to rerun the MacOS tests in the Github Actions several times due to the following error:

```
Run cd test/providers/keychain && ./start && ./test && ./stop
Cleanup: Removed test secrets from Keychain.
=== RUN   TestKeychainProvider
    keychain_provider_test.go:24: The user name or passphrase you entered is not correct. (-25293)
--- FAIL: TestKeychainProvider (0.03s)
FAIL
FAIL	github.com/cyberark/secretless-broker/test/providers/keychain	0.325s
FAIL
Error: Process completed with exit code 1.
```

This appears to be an unstable test. We should figure out what's going on here and fix it.

**Comment by john-odonnell** [comment]
The failure experienced here is connected to an issue in version `20210801.1` of GitHub Actions' macOS 10.15 virtual environment, where MacOS Security tools fail with `errSecAuthFailed (-25293)`.

The issue was reported at actions/virtual-environments#3861, and resolved in recent versions of the virtual env.
