### ISSUE TITLE
StartSecretless Interface exists

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#876]
This is the interface for the top level method that runs secretless.  It will either replace or be called by what is currently `entrypoint`.  Much of the logic currently in `plugin.Manager` will be moved here, and `plugin.Manager` will go away. 

The interface itself will likely have only a single `Run()` method.  However, "designing the interface" here means listing precisely what collaborators will be given to it on construction, and what it's responsibilities are.

AC:
- [ ] Determine the collaborators it will need.
- [ ] Create the `NewStartSecretless` method that will accept those collaborators.
- [ ] Document what `Run()` will do.

**Comment by izgeri** [comment]
Note: in this issue the logic around reloading Secretless plugins when a new configuration is detected may be removed, but the logic for detecting config changes (eg [fs watcher](https://github.com/cyberark/secretless-broker/blob/master/internal/app/secretless/configurationmanagers/configfile/fs_watcher.go) and [crd watcher](https://github.com/cyberark/secretless-broker/blob/master/internal/app/secretless/configurationmanagers/kubernetes/crd/crd_watcher.go)) should remain in the codebase so that we can restore the dynamic config reloading functionality in #881
