### ISSUE TITLE
Convert integration tests to use configs.v2

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#990]
Currently our integration tests for PG and MySQL create generated configuration files for secretless that are designed for `config.v1` which has in at least one case caused unexpected problems in the product. These config generators need to be converted to `config.v2`.

AC:
- [ ] Broker's PG integration tests use `config.v2` configs
- [ ] Broker's MySQL integration tests use `config.v2` configs

**Comment by vladdoster** [comment]
Hi @sgnn7, is this still open for a first time contributor? I enjoyed a [CyberArk article on this piece of software](https://www.conjur.org/blog/open-source-how-to-eat-your-own-dog-food/) and thought I'd contribute.

**Comment by sgnn7** [comment]
@vladdoster Absolutely and we would love to have more contributors to the codebase! Just make sure to read through the [contribution](https://github.com/cyberark/secretless-broker/blob/master/CONTRIBUTING.md) doc first. There's a contributor agreement that you can just send us which is somewhat of a pain but you only need to do this one.

**Comment by vladdoster** [comment]
Hi @sgnn7,

You'll have to bear with me as I am new to Go. I just have a few questions before I proceed further. 

So I was able to track down where the MySql and PG created there configs. It seemed to be in generate_secretless_yml.go. In my [branch](https://github.com/vladdoster/secretless-broker/blob/2968ad5451c0b3e183658e84642fc1fc2193803a/test/util/testutil/cmd/generate_secretless_yml.go#L14) I have added code which seems to take the generated v1 config and converts it to the v2 structure. I have commented it out because it was throwing an error. However, when I run the ./bin/test with my v2 conversion solution, it seems to write the correct structure. See attached screenshot.

![pic-selected-191113-2233-27](https://user-images.githubusercontent.com/10052309/68825554-7951f080-0668-11ea-93bc-5268a20aa432.png)

However it seems to error in MySQL test. Do I need to update the unit tests to take the updated config or is the way I tried converting the v1 config way off? Would love to work through this and fix the issue :smile:. 

btw - The shell scripts you all have written are top notch :+1:

**Comment by sgnn7** [comment]
Hey @vladdoster!

> You'll have to bear with me as I am new to Go. I just have a few questions before I proceed further

Don't worry about asking questions and you're on the right track!

The optimal choice here is to not use v1 configuration at all in the configuration generation if possible since v1 will be removed in one of the future releases so depending on it will make us need to rework this code one more time later. To do the conversion, we might require some changes to the generation code so instead of it creating v1 structs we will now be creating v2 structs from the start.

> Do I need to update the unit tests to take the updated config

I think that unit tests should not be failing if you change this but integration tests for mysql and pg might since those are the ones that depend on this functionality.

> Would love to work through this and fix the issue 😄.

We will help you out whichever way we can!

> btw - The shell scripts you all have written are top notch 👍

<3

**Comment by vladdoster** [comment]
@sgnn7 I agree my solution was terse because I wasn't sure how much backwards compatibility was an issue. I did see in one of the scripts stout that v1 would be deprecated so I guess I should have taken the hint.

**Comment by izgeri** [comment]
@vladdoster can you also make sure to sign your commits by running `git commit` with the `-s` or `--signoff` flag? We're going to be migrating to the DCO for contributions soon.

**Comment by vladdoster** [comment]
> @vladdoster can you also make sure to sign your commits by running `git commit` with the `-s` or `--signoff` flag? We're going to be migrating to the DCO for contributions soon.

I can do that. Sorry about glancing over that in my I initial commit.

**Comment by izgeri** [comment]
I don't think there's anything publicly published about it yet, so you couldn't have known 🙂 I'm hoping to get it updated before you submit your contribution so that it'll be easier for you.

If you need any help with it or have any questions, please let us know!
